routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Order\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HomeController::class)->name('home');



Route::resource('order', OrderController::class);
Route::get('preview/{order}', [OrderController::class, 'preview'])->name('order.preview');
Route::post('postPreview', [OrderController::class, 'postPreview'])->name('order.postPreview');
Route::get('viewState/{id}', [OrderController::class, 'viewState'])->name('order.viewState');
Route::get('retryPay/{id}', [OrderController::class, 'retryPay'])->name('order.retryPay');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    public function customer(){
        
        return $this->belongsTo('App\Models\Customer');
    }

    public function status(){
        
        return $this->belongsTo('App\Models\Status');
    }
}

app/Http/Controllers/Order/OrderController.php
<?php

namespace App\Http\Controllers\Order;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Utils\Helpers;

use App\Http\Requests\StoreOrder;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->utils = new Helpers();
        $this->status = [
            'CREATED' => 1,
            'REJECTED' => 2,
            'APPROVED' => 3,
            'PENDING' => 4
        ];
    }
    public function index(){
        $orders = Order::orderBy('id','desc')->paginate(5);
        return view('Order.Order.index', compact('orders'));
    }

    public function create(){
        return view('Order.Order.create');
    }

    public function store(StoreOrder $request){

        $customer = Customer::create($request->all());
        
        $order = new Order();

        $order->status_id = 1;
        $order->customer_id = $customer->id;
        $order->product_id = 1;

        $order->save();

        return redirect()->route('order.preview', $order->id);
    }

    public function show(Order $order){
        return view('Order.Order.show', compact('order'));
    }

    public function edit(Customer $order){
        return view('Order.Order.edit', compact('order'));
    }

    public function update(StoreOrder $request, Customer $order){

        $order->update($request->all());

        return redirect()->route('order.show', $order->id);
    }

    public static function updateOrder($id, $status, $id_request = false, $process_url = false)
    {
        $orders = Order::find($id);
        $orders->status_id = $status;
        if($id_request){
            $orders->id_request = $id_request;
            $orders->process_url = $process_url;
        }
        if (!$orders->save()) {
            return false;
        }
        return $orders;
    }

    public function preview($id)
    {
        $order = Order::find($id);
        if($order == null || empty($order) ){
            return redirect()->route('order.create')->withErrors(['errors' => 'El id especificado no existe']);
        }
        $customer = Customer::find($order->customer_id);
        return view('Order.Order.preview', compact('order','customer'));
    }

    public function postPreview(Request $request)
    {

        $order = Order::find($request['id_orden']);
        if($order == null || empty($order) ){
            return redirect()->route('order.create');
        }
        $responseWs = $this->utils->createSessionPlacetoPay($order->id);
        
        if ($responseWs['status']['status'] === 'OK' && $responseWs['status']['reason'] === 'PC') {
            $this->updateOrder($order->id, 1, $responseWs['requestId'], $responseWs['processUrl']);
            return redirect($responseWs['processUrl']);
        } else {
            $customer = Customer::find($order->customer_id);
            return redirect()->route('order.preview',$order->id,$customer)->withErrors(['errors' => 'Ocurrio un error al consumir el servicio, por favor intentar mas tarde']);
        }
    }

    public function viewState($id)
    {
        $statusTra = [
            'CREATED' => 'Creada',
            'REJECTED' => 'Rechazada',
            'APPROVED' => 'Pagada',
            'PENDING' => 'Pendiente'
        ];
        $order = Order::find($id);
        if($order == null || empty($order) ){
            return redirect()->route('order.show');
        }
        $customer = Customer::find($order->customer_id);
        if($order->id_request !== null){
            $response = $this->utils->getRequestInformation($order->id_request);
            $this->updateOrder($order->id, $this->status[$response['status']['status']]);
            return view('Order.Order.statusOrder', compact('response', 'statusTra', 'order'));
        }else{

            return view('Order.Order.preview', compact('order','customer'));
        }
    }
}

resources/views/Order/Order/create.blade.php
@extends('layouts.main')

@section('title', 'Confirm Purchase')

@section('content')
    <h1>Confirm Purchase</h1><br>
    <form action="{{route('order.store')}}" method="POST">

        <label>
            <span class="title">In Cart</span> <br><img src="{{asset('img/tshirt.jpg')}}" alt=""><br><span class="title">$15</span>
        </label><br><br>

        @csrf
        <label>
            Name
            <br>
            <input type="text" name="customer_name" value="{{old('customer_name')}}">
        </label>
        @error('customer_name')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <label>
            Email
            <br>
            <input type="email" name="customer_email" value="{{old('customer_email')}}">
        </label>
        @error('customer_email')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <label>
            Mobile Phone
            <br>
            <input type="text" name="customer_mobile" value="{{old('customer_mobile')}}">
        </label>
        @error('customer_mobile')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <button class="btn btn-success" type="submit">Continue to checkout</button>
    </form>
@endsection

resources/views/Order/Order/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit')

@section('content')
    <h1>create orden</h1>
    <form action="{{route('order.update', $order)}}" method="POST">
        @csrf

        @method('put')
        <label>
            Nombre
            <br>
            <input type="text" name="customer_name" value="{{ old('customer_name',$order->customer_name) }}">
        </label>
        @error('customer_name')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <label>
            Correo
            <br>
            <input type="email" name="customer_email" value="{{ old('customer_email',$order->customer_email) }}">
        </label>
        @error('customer_email')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <label>
            Celular
            <br>
            <input type="text" name="customer_mobile" value="{{ old('customer_mobile',$order->customer_mobile) }}">
        </label>
        @error('customer_mobile')
            <br>
            <small>*{{$message}}</small>
            <br>
        @enderror
        <br>
        <button type="submit">Actualizar</button>
    </form>
@endsection

resources/views/Order/Order/index.blade.php
@extends('layouts.main')

@section('title', 'Index')

@section('content')
    <h1>Orders from the Store</h1>
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>Customer</th>
            <th>Status</th>
        </tr>
        @foreach ($orders as $order)
            <tr>
                <td>{{$order->id}}</td>
                <td>{{$order->customer->customer_name}}</td>
                <td>
                    @if($order->status_id != '3')
                        <a class="btn btn-warning" href="{{route('order.viewState',['id'=>$order->id])}}"> {{ $order->status->status_description }}</a>
                    @else
                        {{ $order->status->status_description }}
                    @endif
                </td>
            </tr>
        @endforeach
    </table>

    {{$orders->links()}}
@endsection

resources/views/Order/Order/preview.blade.php
@extends('layouts.main')
@section('title', 'Order Preview')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <p>Se han produccido los siguientes errores:</p>
            <ul>
                @foreach ($errors->all() as $message)
                    <li>{{ $message }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <h1>Resumen de la compra</h1>
        <img src="{{asset('img/tshirt.jpg')}}" alt="">
            <div>
                <h3>DualShock Controller for PlayStation 4</h3>
                <div class="mb-2">
                    $15
                </div>
                <div class="clearfix"></div>
            </div>
    <div class="container">
        <div style="display: flex;  align-items: center;  justify-content: center;">
            <form method="POST" action="{{ route('order.postPreview') }}">
                @csrf

                <legend>Necesary data</legend>
                <div class="form-group">
                    <label for="name" class="form-label">Nombre</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Ingrese su nombre"
                           maxlength="80" value="{{ old('customer_name',$customer->customer_name) }}" required readonly>
                </div>
                <div class="form-group">
                    <label for="email" class="form-label">Email *</label>
                    <input type="email" id="email" name="email" class="form-control"
                           placeholder="Ingrese su correo electr&oacute;nico" maxlength="120" value="{{ old('customer_email',$customer->customer_email) }}" required readonly>
                </div>
                <div class="form-group">
                    <label for="mobile" class="form-label">Celular *</label>
                    <input type="number" id="mobile" name="mobile" class="form-control"
                           placeholder="Ingrese su numero de celular" maxlength="40" value="{{ old('customer_mobile',$customer->customer_mobile) }}" required readonly>
                </div>
                <div>
                    <input type="hidden" name="id_orden" value="{{$order->id}}">
                    <a href="{{route('order.create', ['id' => $order->id])}}" type="submit" class="btn btn-primary m-5">Volver</a>
                    <button type="submit" class="btn btn-primary m-5">Comprar</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Order/Order/show.blade.php
@extends('layouts.main')

@section('title', 'Index')

@section('content')
    <h1>My order #{{$order->id}}</h1>
    <table>
        <tr>
            <th>#</th>
            <th>Customer</th>
            <th>Status</th>
        </tr>
        <tr>
            <td>{{$order->id}}</td>
            <td>{{$order->customer->customer_name}}</td>
            <td>
                @if($order->status_id != '3')
                    <a class="btn btn-warning" href="{{route('order.viewState',['id'=>$order->id])}}"> {{ $order->status->status_description }}</a>
                @else
                    {{ $order->status->status_description }}
                @endif
            </td>
        </tr>
    </table>

@endsection

resources/views/Order/Order/statusOrder.blade.php
@extends('layouts.main')
@section('title', 'Status order')
@section('content')
    <label>
        <span class="title">In Cart</span> <br><img src="{{asset('img/tshirt.jpg')}}" alt=""><br><span class="title">$15</span>
    </label><br><br>
    
    <div class=" align-items-center">
        <div class="col-12 text-center">
            <h2>Estado del producto</h2>
        </div>
        <div class="col-12 text-center">
            <label> Estado del producto: <strong>{{$statusTra[$response['status']['status']]}}</strong> </label>
        </div>
        <div class="col-12 text-center">
            <label> Detalles: {{$response['status']['message']}} </label>
        </div>
        @if($response['status']['status'] == 'REJECTED')
            <div class="col-12 text-center p-2">
                <a class="btn btn-danger" href="{{route("retryPayOrder", ['id' => $order->id])}}" role="button">Reintentar</a>
            </div>
        @endif
        @if($response['status']['status'] == 'PENDING')
            <div class="col-12 text-center p-2">
                <a class="btn btn-warning" href="{{$order->process_url}}" role="button">Reintentar</a>
            </div>
        @endif
        <div class="col-12 text-center p-2">
            <a href="{{route('order.show',$order->id)}}" class="btn btn-primary" >Listar ordenes</a>
        </div>
    </div>
@endsection