routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Order\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HomeController::class)->name('home');



Route::resource('order', OrderController::class);
Route::get('preview/{order}', [OrderController::class, 'preview'])->name('order.preview');
Route::post('postPreview', [OrderController::class, 'postPreview'])->name('order.postPreview');
Route::get('viewState/{id}', [OrderController::class, 'viewState'])->name('order.viewState');
Route::get('retryPay/{id}', [OrderController::class, 'retryPay'])->name('order.retryPay');

resources/views/layouts/partials/footer.blade.php
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

resources/views/layouts/partials/head.blade.php
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@yield('title')</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="{{ asset('css/app.css') }}">

resources/views/layouts/partials/header.blade.php
<header>
    <h1>Tienda Online</h1>
    <nav>
        <ul>
            <li><a href="{{route('home')}}" class="{{ request()->routeIs('home') ? 'active' : '' }}">Home</a></li>
            <li><a href="">My orders</a></li>
            <li><a href="{{route('order.index')}}" class="{{ request()->routeIs('order.index') ? 'active' : '' }}">Store orders</a></li>
        </ul>
    </nav>
</header>